# NumPy  ( Numerical Python)

In [1]:
import numpy as np

In [3]:
## NumPy Array oluşturmak;
np.array=([1,2,3,4])

In [2]:
a = np.array([1,2,3,4])

In [4]:
np.array(["a",1])

array(['a', '1'], dtype='<U1')

In [5]:
np.array([3.14,4,5])  # tek bir bilgi tuttuğu için hepsini aynı türe dönüştürdü

array([3.14, 4.  , 5.  ])

In [6]:
np.array([3.14,6,7,1.12,6.8,4], dtype="int")  # veri tiplerini integer a dönüştürdü

array([3, 6, 7, 1, 6, 4])

In [7]:
# içerisinde 10 tane  0 lardan oluşan  integer tipinde array oluşturdu
np.zeros(10, dtype=int)    

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# içerisinde belirtiten satır ve sütün sayısınca 1 lerden oluşan  integer tipinde array oluşturdu
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
# içerisinde belirtiten satır ve sütün sayısınca hangi sayıdan oluşturulmasını istersek (3) integer tipinde array oluşturdu
np.full((3,5),3,dtype=int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [12]:
# içerisinde belirtilen sayı aralığında(0,31) kaçar kaçar artmasını istediğimiz sayıca(3) array oluşturuldu

np.arange(0,31, 3) # 0 dan 31  e üçer üçer artacak doğrusal bir dizi oluşturuldu.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
# belirtilen sayı aralığında (1,30) üretilmek istenen sayı miktarıca (10) array oluşturuldu 
np.linspace(1,30,10, dtype=int)
np.linspace(1,30,10)

array([ 1.        ,  4.22222222,  7.44444444, 10.66666667, 13.88888889,
       17.11111111, 20.33333333, 23.55555556, 26.77777778, 30.        ])

In [2]:
# oluşturulan rastgele sayılardan belli bir istatistik dağılıma uygun olmasını istersek;
#örn/ normal dağılım için belli bir standart sapma(4) ve ortalama(10) belirlenmiş olsun,istediğimiz boyutta(3,4) array oluşturur
np.random.normal(10,4,(3,4))

array([[ 6.40910319, 15.64875081, 12.98725771,  6.99379174],
       [10.53244938, 11.75558924,  9.31587835, 11.39028822],
       [ 7.85806652,  9.56783182,  9.05863542,  9.4848442 ]])

In [3]:
# belli aralıkta (0,10) rastgele sayılardan belirtilen boyutta (3,6) integer bir array oluşturulmak istenirse;
np.random.randint(0,10,(3,6))

array([[6, 3, 1, 5, 0, 5],
       [5, 4, 3, 4, 9, 7],
       [0, 8, 8, 7, 6, 1]])

 ## Özellikler
* **ndim:** boyut sayısı
* **shape:** boyut bilgisi
* **size:** toplam elaman 
* **dtype:** array veri tipi

In [7]:
np.random.randint(10,size=8)

array([0, 2, 9, 2, 5, 5, 1, 9])

In [8]:
a=np.random.randint(10,size=8)

In [14]:
print(a.ndim,"->>boyutu")  #boyutu
print(a.shape,"->>boyut bilgisi")
print(a.size,"->>eleman sayisi")
print(a.dtype,"->>array tipi")

1 ->>boyutu
(8,) ->>boyut bilgisi
8 ->>eleman sayisi
int32 ->>array tipi


In [16]:
b=np.random.randint(10,size=(3,5))

In [17]:
print(b.ndim,"->>boyutu")  #boyutu
print(b.shape,"->>boyut bilgisi")
print(b.size,"->>eleman sayisi")
print(b.dtype,"->>array tipi")

2 ->>boyutu
(3, 5) ->>boyut bilgisi
15 ->>eleman sayisi
int32 ->>array tipi
