# NumPy  ( Numerical Python)

In [2]:
import numpy as np

In [3]:
## NumPy Array oluşturmak;
np.array=([1,2,3,4])

In [2]:
a = np.array([1,2,3,4])

In [4]:
np.array(["a",1])

array(['a', '1'], dtype='<U1')

In [5]:
np.array([3.14,4,5])  # tek bir bilgi tuttuğu için hepsini aynı türe dönüştürdü

array([3.14, 4.  , 5.  ])

In [6]:
np.array([3.14,6,7,1.12,6.8,4], dtype="int")  # veri tiplerini integer a dönüştürdü

array([3, 6, 7, 1, 6, 4])

In [7]:
# içerisinde 10 tane  0 lardan oluşan  integer tipinde array oluşturdu
np.zeros(10, dtype=int)    

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# içerisinde belirtiten satır ve sütün sayısınca 1 lerden oluşan  integer tipinde array oluşturdu
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
# içerisinde belirtiten satır ve sütün sayısınca hangi sayıdan oluşturulmasını istersek (3) integer tipinde array oluşturdu
np.full((3,5),3,dtype=int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [12]:
# içerisinde belirtilen sayı aralığında(0,31) kaçar kaçar artmasını istediğimiz sayıca(3) array oluşturuldu

np.arange(0,31, 3) # 0 dan 31  e üçer üçer artacak doğrusal bir dizi oluşturuldu.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
# belirtilen sayı aralığında (1,30) üretilmek istenen sayı miktarıca (10) array oluşturuldu 
np.linspace(1,30,10, dtype=int)
np.linspace(1,30,10)

array([ 1.        ,  4.22222222,  7.44444444, 10.66666667, 13.88888889,
       17.11111111, 20.33333333, 23.55555556, 26.77777778, 30.        ])

In [2]:
# oluşturulan rastgele sayılardan belli bir istatistik dağılıma uygun olmasını istersek;
#örn/ normal dağılım için belli bir standart sapma(4) ve ortalama(10) belirlenmiş olsun,istediğimiz boyutta(3,4) array oluşturur
np.random.normal(10,4,(3,4))

array([[ 6.40910319, 15.64875081, 12.98725771,  6.99379174],
       [10.53244938, 11.75558924,  9.31587835, 11.39028822],
       [ 7.85806652,  9.56783182,  9.05863542,  9.4848442 ]])

In [3]:
# belli aralıkta (0,10) rastgele sayılardan belirtilen boyutta (3,6) integer bir array oluşturulmak istenirse;
np.random.randint(0,10,(3,6))

array([[6, 3, 1, 5, 0, 5],
       [5, 4, 3, 4, 9, 7],
       [0, 8, 8, 7, 6, 1]])

 ## Özellikler
* **ndim:** boyut sayısı
* **shape:** boyut bilgisi
* **size:** toplam elaman 
* **dtype:** array veri tipi

In [7]:
np.random.randint(10,size=8)

array([0, 2, 9, 2, 5, 5, 1, 9])

In [8]:
a=np.random.randint(10,size=8)

In [14]:
print(a.ndim,"->>boyutu")  #boyutu
print(a.shape,"->>boyut bilgisi")
print(a.size,"->>eleman sayisi")
print(a.dtype,"->>array tipi")

1 ->>boyutu
(8,) ->>boyut bilgisi
8 ->>eleman sayisi
int32 ->>array tipi


In [16]:
b=np.random.randint(10,size=(3,5))

In [17]:
print(b.ndim,"->>boyutu")  #boyutu
print(b.shape,"->>boyut bilgisi")
print(b.size,"->>eleman sayisi")
print(b.dtype,"->>array tipi")

2 ->>boyutu
(3, 5) ->>boyut bilgisi
15 ->>eleman sayisi
int32 ->>array tipi


# *Yeniden Şekillendirme (reshaping)*

 var olan arrayin satır sütun sayılarından istenilen sayılara dönüştürülmesidir

In [3]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(1,10).reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
a=np.arange(1,10)

In [10]:
a.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**tek boyut bilgilerini kaybetmeden çift boyuta taşınmak istenirse;**

In [16]:
b=np.arange(1,10)

In [17]:
b.ndim  # tek boyutlu

1

In [18]:
c=b.reshape(1,9)

In [19]:
c.ndim 

2

# _Array Birleştirme (Concatenation)_

farklı arraylerin birleştirilmesi sağlanır

In [25]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.array([7,8,9])

In [26]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

**iki boyutta birleştirmeler için;**

In [27]:
a=np.array([[1,2,3],
           [4,5,6]])

In [29]:
np.concatenate([a,a])  # axis değeri default olarak satır  bazında birleştirme yapar yani axis=0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

* **Not : _axis eksen belirtmek için kullanılır 0 satırları , 1 sütunları ifade eder._**

In [30]:
np.concatenate([a,a],axis=1)  # sütun bazlı birleştirme yapıldı

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# _Array Ayırma (Splitting)_

In [38]:
x=np.array([1,2,3,99,99,3,2,1])

In [39]:
np.split(x,(3,5))  # (3,5) ifadesinde 3 -e kadar daha sonra 5 e kadar ayır anlamına gelir 


[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [40]:
# ayrılan arrayleri değişkene atamak istersek;
a,b,c=np.split(x,(3,5))

In [41]:
print("a arrayi : -> ",a)
print("b arrayi : -> ",b)
print("c arrayi : -> ",c)

a arrayi : ->  [1 2 3]
b arrayi : ->  [99 99]
c arrayi : ->  [3 2 1]


**iki boyutta ayırma için;**

In [43]:
m=np.arange(16).reshape(4,4)
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
np.vsplit(m,(2))  # satırdan 2.index -e kadar  böl

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [50]:
np.hsplit(m,(2)) # sütundan 2. index -e kadar böl

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [51]:
np.hsplit(m,(4)) 

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1],
        [ 5],
        [ 9],
        [13]]),
 array([[ 2],
        [ 6],
        [10],
        [14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

# **_Sıralama (sorting)_**

In [53]:
v=np.array([2,1,4,3,5])
v

array([2, 1, 4, 3, 5])

In [70]:
np.sort(v)

array([1, 2, 3, 4, 5])

**iki boyutta sıralama için;**

In [68]:
h=np.random.normal(20,5,(3,3))
h

array([[17.88527889, 13.74677418, 22.99599695],
       [20.55913492, 11.46723385, 22.32396419],
       [22.21855577, 17.44782855, 11.98136527]])

In [69]:
np.sort(h,axis=1)   # satır bazlı küçükten büyüğe doğru sıraladı

array([[13.74677418, 17.88527889, 22.99599695],
       [11.46723385, 20.55913492, 22.32396419],
       [11.98136527, 17.44782855, 22.21855577]])

In [67]:
np.sort(h,axis=0) # sütun bazlı küçükten büyüğe sıralama yaptı

array([[18.94283545, 15.66148587, 20.44505109],
       [21.13070019, 17.57464401, 21.91499303],
       [24.73302522, 21.07500842, 31.86930218]])

# **_Index ile Elemanlara Erişmek_**

In [10]:
a=np.random.randint(10,size=10)
a

array([9, 7, 6, 4, 5, 2, 2, 7, 7, 2])

In [11]:
print("ilk eleman-->",a[0])
print("son eleman-->",a[-1])

ilk eleman--> 9
son eleman--> 2


In [7]:
a[0]=100 # eleman değiştirmek için

In [8]:
a

array([100,   2,   4,   8,   1,   0,   6,   4,   8,   9])

In [17]:
m=np.random.randint(12,size=(3,4))
m

array([[11,  7, 10,  1],
       [ 4, 10,  5,  2],
       [ 9,  5,  9,  5]])

In [19]:
m[0,1]   # 0. satırın 1. sütunu

7

In [18]:
m[2,0]=99
m

array([[11,  7, 10,  1],
       [ 4, 10,  5,  2],
       [99,  5,  9,  5]])