# NumPy  ( Numerical Python)

In [1]:
import numpy as np

In [3]:
## NumPy Array oluşturmak;
np.array=([1,2,3,4])

In [2]:
a = np.array([1,2,3,4])

In [4]:
np.array(["a",1])

array(['a', '1'], dtype='<U1')

In [5]:
np.array([3.14,4,5])  # tek bir bilgi tuttuğu için hepsini aynı türe dönüştürdü

array([3.14, 4.  , 5.  ])

In [6]:
np.array([3.14,6,7,1.12,6.8,4], dtype="int")  # veri tiplerini integer a dönüştürdü

array([3, 6, 7, 1, 6, 4])

In [7]:
# içerisinde 10 tane  0 lardan oluşan  integer tipinde array oluşturdu
np.zeros(10, dtype=int)    

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [9]:
# içerisinde belirtiten satır ve sütün sayısınca 1 lerden oluşan  integer tipinde array oluşturdu
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
# içerisinde belirtiten satır ve sütün sayısınca hangi sayıdan oluşturulmasını istersek (3) integer tipinde array oluşturdu
np.full((3,5),3,dtype=int)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [12]:
# içerisinde belirtilen sayı aralığında(0,31) kaçar kaçar artmasını istediğimiz sayıca(3) array oluşturuldu

np.arange(0,31, 3) # 0 dan 31  e üçer üçer artacak doğrusal bir dizi oluşturuldu.

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [16]:
# belirtilen sayı aralığında (1,30) üretilmek istenen sayı miktarıca (10) array oluşturuldu 
np.linspace(1,30,10, dtype=int)
np.linspace(1,30,10)

array([ 1.        ,  4.22222222,  7.44444444, 10.66666667, 13.88888889,
       17.11111111, 20.33333333, 23.55555556, 26.77777778, 30.        ])